#!/bin/bash
CONFIG_TEMPLATE="${TRIM_APPDEST}/template/aria2.tpl"
CONFIG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/data/aria2.conf"
TARGET_DIR="${TRIM_DATA_SHARE_PATHS%%:*}/data"

sed \
  -e "s|\${PRC_SECRET}|$rpc_secret|g" \
  "$CONFIG_TEMPLATE" > "$CONFIG_FILE"
  
if [ ! -f "$TARGET_DIR/aria2.session" ]; then
    touch "$TARGET_DIR/aria2.session"
fi

exit 0