#!/bin/bash
case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    exit 0
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    exit 0
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    exit 0
    ;;
log)
    exit 0
    ;;
*)
    exit 1
    ;;
esac