#!/bin/bash

sed -i \
  -e "s#<HttpServerPortNumber>[^<]*</HttpServerPortNumber>#<HttpServerPortNumber>${ui_port}</HttpServerPortNumber>#" \
  -e "s#<PublicPort>[^<]*</PublicPort>#<PublicPort>${ui_port}</PublicPort>#" \
  "${TRIM_PKGVAR}/config/system.xml"

exit 0
