#!/bin/bash

cd ${TRIM_APPDEST}/server
tar -xJf node_modules.tar.xz
rm -f node_modules.tar.xz

mkdir -p ${TRIM_PKGVAR}/config ${TRIM_PKGVAR}/cache

ln -sfn ${TRIM_APPDEST}/utils/poppler-utils ${TRIM_APPDEST}/utils/pdftotext

exit 0
