#!/bin/bash
LOG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/data/info.log"
CONFIG_TEMPLATE="${TRIM_APPDEST}/template/settings.tpl"
CONFIG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/data/settings.json"

if [ -f "$CONFIG_FILE" ]; then
    echo "配置已存在，跳过初始化" >> ${LOG_FILE}
else
    sed \
      -e "s|\${USER_NAME}|$user_name|g" \
      -e "s|\${USER_PASSWORD}|$user_password|g" \
      -e "s|\${RPC_PORT}|$rpc_port|g" \
      "$CONFIG_TEMPLATE" > "$CONFIG_FILE"
    echo "基础配置已初始化" >> ${LOG_FILE}
fi


exit 0