#!/bin/bash

cd ${TRIM_APPDEST}
tar -xzf server.tar.gz
rm -rf server.tar.gz
mkdir -p ${TRIM_PKGVAR}/node
mv node.tar.xz ${TRIM_PKGVAR}/node/node.tar.xz

cd ${TRIM_PKGVAR}/node
tar -xf node.tar.xz --strip-components=1
rm -f node.tar.xz

exit 0
