#!/bin/bash
cd ${TRIM_APPDEST}
tar -xJf node_modules.tar.xz
rm -f node_modules.tar.xz

mkdir ${TRIM_PKGVAR}/logs
mkdir ${TRIM_PKGVAR}/data
ln -s ${TRIM_PKGVAR}/data ${TRIM_APPDEST}/data
ln -s ${TRIM_PKGVAR}/logs ${TRIM_APPDEST}/logs

exit 0
