#!/bin/bash
export PATH=/var/apps/nodejs_v24/target/bin:$PATH
export PATH=${TRIM_APPDEST}/nginx:$PATH
LOG_FILE="${TRIM_PKGVAR}/logs/info.log"
PID_FILE="${TRIM_PKGVAR}/nginx.pid"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi
  
    log_msg "Starting process ..."
    # run cmd to start process
    cd ${TRIM_APPDEST}
    npm run start >> ${LOG_FILE} 2>&1 &
    bash -c nginx-cs >> ${LOG_FILE} 2>&1 &
    return 0
}

stop_process() {
    log_msg "Stopping process..."

    # 发送 SIGTERM 信号，请求进程优雅关闭
    log_msg "正在请求 'nginx-cs' 和 'MainThread' 进程关闭..."
    pkill -TERM -u CloudSaver -x "nginx-cs"
    pkill -TERM -u CloudSaver -x "MainThread"

    # 循环等待，直到 'nginx-cs' 和 'MainThread' 进程都不再存在
    while pgrep -u CloudSaver -x "nginx-cs" > /dev/null || pgrep -u CloudSaver -x "MainThread" > /dev/null; do
        # 检查哪个进程还在运行，并打印相应日志
        if pgrep -u CloudSaver -x "nginx-cs" > /dev/null; then
            log_msg "进程 'nginx-cs' 仍在运行，等待中..."
        fi
        if pgrep -u CloudSaver -x "MainThread" > /dev/null; then
            log_msg "进程 'MainThread' 仍在运行，等待中..."
        fi
        sleep 1
    done
    
    log_msg "进程 'cloudsaver-nginx' 和 'MainThread' 均已成功关闭。"

    # 清理 PID 文件
    if [ -f "${PID_FILE}" ]; then
        rm -f "${PID_FILE}"
        log_msg "已删除 PID 文件: ${PID_FILE}"
    fi

    log_msg "CloudSaver 进程已停止"
    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac