#!/bin/bash
export PATH=/var/apps/nodejs_v24/target/bin:$PATH
cd ${TRIM_APPDEST}
tar -xzf server.tar.gz
rm -f server.tar.gz
mkdir -p ${TRIM_PKGVAR}/pnpm
mkdir -p ${TRIM_PKGVAR}/backup
corepack enable pnpm --install-directory ${TRIM_PKGVAR}/pnpm

exit 0
