#!/bin/bash
export PATH=/var/apps/nodejs_v24/target/bin:$PATH
export HOME="${TRIM_DATA_SHARE_PATHS%%:*}"
export PNPM_HOME="${TRIM_PKGVAR}/pnpm"
export PROXY_PORT="$port"
export PROXY_PASSWORD="$password"
export PROXY_AUTH="$auth_mode"
if [ "$proxy_mode" = "1" ];then
    export http_proxy="$proxy_addr"
    export https_proxy="$proxy_addr"
else
    unset http_proxy
    unset https_proxy
fi

LOG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here 
CMD="node apps/cli/lib/bin.js web --no-open"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    if status; then
        return 0
    fi

    log_msg "Starting process ..."
    cd ${TRIM_APPDEST}/server
    bash -c "${CMD}" >> ${LOG_FILE} 2>&1 &
    sleep 2
    nohup node ${TRIM_APPDEST}/proxy.js 2>&1 &
    printf "%s" "$!" > ${PID_FILE}
    return 0
}

stop_process() {
    log_msg "Stopping process ..."

    pkill -TERM -u Harness -x "MainThread" >> ${LOG_FILE} 2>&1
        
    while pgrep -u Harness -x "MainThread" > /dev/null; do
        # 检查哪个进程还在运行，并打印相应日志
        if pgrep -u Harness -x "MainThread" > /dev/null; then
            log_msg "进程 'MainThread' 仍在运行，等待中..."
        fi
        sleep 1
    done

    rm -f "${PID_FILE}"
    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
